### ISSUE TITLE
Automate communication to PIs to let them know what they have running

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openshift-usage-scripts#16] opened 2023-12-07 19:20 UTC
## Motivation
since we do not yet have live tracking of hardware we want to make sure users know what they currently have running.

## Completion Criteria
automated email sent to let PIs know what pods/vm are running

## Description
- [ ] Automade a list of pods/vms per PI
- [ ] automate emailing those PIs
   - does it need to go to managers as well?
- [ ] test

## Completion dates
Desired - 2023-12-22
Required - TBD

**Comment by msdisme** [comment] 2023-12-20 15:16
Close as less detailed duplicate of https://github.com/nerc-project/operations/issues/344 - move 344 to jan 3 sprint - ask question in 344 if it should be moved to https://github.com/CCI-MOC/openshift-usage-scripts

**Closed by msdisme** 2023-12-20 15:16 UTC
